### ISSUE TITLE
Possibly remove the fake virtualenv in tox_cleanup hook

### ISSUE THREAD

**Issue by hroncok** [fedora-python/tox-current-env#14]
If we delete the fake virtualenv in the [tox_cleanup hook](https://tox.readthedocs.io/en/latest/plugins.html#tox.hookspecs.tox_cleanup), we may avoid the entire "running regular after current env is unsupported" thing.

Removing and recreating the fake virtualenv is cheap.

Obviously, it has some problems - if tox is forcefully  killed, the hook might not get called, so we need to keep the check forever, but it will be less likely to happen.

**Comment by encukou** [comment]
Could we also add some a marker file next to the symlink, remove it in cleanup (along with the whole fake venv), and fail "regular" tox runs if it's still there?
That way you'd need to forcefully kill tox *and* uninstall the plugin to get in trouble.

**Comment by hroncok** [comment]
The idea was the same except for the marker.

**Comment by encukou** [comment]
I see. Never mind me!
