### ISSUE TITLE
Remove `pip` dependency

### ISSUE THREAD

**Issue by FFY00** [fedora-python/tox-current-env#31]
Would it be possible to remove the `pip` dependency? At least optionally.

```
py38 create: /build/python-markdown2/src/python-markdown2-2.3.9/.tox/py38
ERROR: invocation failed (exit code 1), logfile: /build/python-markdown2/src/python-markdown2-2.3.9/.tox/py38/log/py38-0.log
================================== log start ===================================
/build/python-markdown2/src/python-markdown2-2.3.9/.tox/py38/bin/python: No module named pip

=================================== log end ====================================
___________________________________ summary ____________________________________
ERROR:   py38: InvocationError for command /build/python-markdown2/src/python-markdown2-2.3.9/.tox/py38/bin/python -m pip freeze (exited with code 1)
```

It seems like it comes from https://github.com/tox-dev/tox/blob/23dd96f5a6891fb13e298ea941bd457931421ffd/src/tox/config/__init__.py#L846.

If I understand correctly, it could be done [here](https://github.com/fedora-python/tox-current-env/blob/65cb96383bd4ee9a8621702be2b888a77cdaa208/src/tox_current_env/hooks.py#L35), I can send a PR, just let me know how you want to proceed. Do you want to add an option to disable this check? Do you want to replace the command with an alternative one?

`python -m pip freeze` could be replaced with `importlib.metadata`:

```sh
python -c 'import importlib.metadata; print("\n".join("{}=={}".format(d.metadata.get("name"), d.version) for d in importlib.metadata.distributions()))'
```

**Comment by FFY00** [comment]
In my system `importlib.metadata` is also much faster.

Using `pip`:
```
Executed in  810.05 millis    fish           external
   usr time  709.24 millis  308.00 micros  708.93 millis
   sys time   88.71 millis  115.00 micros   88.60 millis
```

Using `importlib.metadata` directly:
```
Executed in  325.28 millis    fish           external
   usr time  296.06 millis  328.00 micros  295.74 millis
   sys time   23.30 millis   47.00 micros   23.25 millis
```

**Comment by hroncok** [comment]
Can we simply not print dependencies?

**Comment by FFY00** [comment]
I don't see any reason why not. And I totally forgot, `tox --print-deps-only` could also be used here.

**Comment by hroncok** [comment]
Ideally, we would just do: `if config.option.current_env or config.option.print_deps_only`, skip this.

**Comment by FFY00** [comment]
Hum, but I want to remove the `pip` dependency when running the tests.

**Comment by hroncok** [comment]
`config.option.current_env` runs the tests.

**Comment by FFY00** [comment]
Ah! That should work then, I will have a look and open a PR :blush:

**Comment by FFY00** [comment]
This can be closed now.

Is there any ETA for a release? Thanks!

**Comment by hroncok** [comment]
I'd like to address https://github.com/fedora-python/tox-current-env/pull/34 and https://github.com/fedora-python/tox-current-env/pull/33 before a new release. Hopefully it should be done more or less in a week.

**Comment by hroncok** [comment]
0.0.3 is out.
