### ISSUE TITLE
Migrate to tox-dev and v4 support

### ISSUE THREAD

**Issue by gaborbernat** [fedora-python/tox-current-env#41]
Hello, would you consider moving the project under the tox-dev umbrella? See documentation under https://tox.readthedocs.io/en/rewrite/plugins.html#adoption-of-a-plugin-under-tox-dev-github-organization 

Furthermore, tox v4 is getting ready and we'd like to make sure this plugin is supported from day 1, we're collecting feature gaps for this under https://github.com/tox-dev/tox/issues/1974. Would be great if you could join our development chat under https://discord.gg/tox so we can assist with this. If you do so please drop in a line in the `#plugin` chat with the name of the repository you maintain. Thanks!

**Comment by gaborbernat** [comment]
Hello, migrating is fully optional 😊so no pressure 🍺

**Comment by hroncok** [comment]
Do you have some rough idea when tox 4 reaches betas and rcs? I'd like to prioritize this accordingly.

**Comment by gaborbernat** [comment]
It can go beta today and start iterating on a release from there. How long that will last will depend on how much change we have to do for accommodating plugins and how many bugs our beta testers find (release blockers are https://github.com/tox-dev/tox/milestone/7).

**Comment by ssbarnea** [comment]
@hroncok tox 4 beta was just launched this morning and guess what package broke it... As first measure I would release a patch that would require `tox<4.0` and start reviewing the #42 for integration.

**Comment by hroncok** [comment]
Yeah, when I saw the beta release, I was thinking we need to pin.

**Comment by hroncok** [comment]
https://github.com/fedora-python/tox-current-env/pull/48

**Comment by jabbera** [comment]
I know this is old, but we have a stable tox 4 out now. Can we get this update pushed?

**Comment by hroncok** [comment]
That is the plan. We are carefully evaluating the impact on Fedora packages. See https://src.fedoraproject.org/rpms/python-tox/pull-request/84#comment-123712

**Comment by hroncok** [comment]
I've just released 0.0.10 with tox 4 support.
