### ISSUE TITLE
No module named tox

### ISSUE THREAD

**Issue by chrisk314** [fedora-python/tox-current-env#43]
When running `tox` with the `--current-env` argument I'm getting an error that the tox module can't be found.

```
$ source .venv-dev/bin/activate
$ which tox
/common/parent/path/.venv-dev/bin/tox
$ tox --current-env -e lint
/common/parent/path/.tox/.tox/bin/python: No module named tox
```

**Comment by hroncok** [comment]
I'm gonna need some more information to be able to help you.

- How did you create `.venv-dev`?
- How did you install tox?
- How did you install tox-current-env?
- How does your tox config look like?
