### ISSUE TITLE
Injecting whitelist_externals break tox.ini files using newer allowlist_externals

### ISSUE THREAD

**Issue by ssbarnea** [fedora-python/tox-current-env#45]
The line at https://github.com/fedora-python/tox-current-env/blob/60d4e23d203cc697e28ea050e4a8db5d4b2bd27f/src/tox_current_env/hooks.py#L75 effectively breaks any tox.ini file that used the newer `allowlist_externals` by causing something like:

```
...
  File "/usr/lib/python3.9/site-packages/tox/venv.py", line 217, in _check_external_allowed_and_warn
    if not self.is_allowed_external(path):
  File "/usr/lib/python3.9/site-packages/tox/venv.py", line 237, in is_allowed_external
    raise tox.exception.ConfigError(
tox.exception.ConfigError: ConfigError: Either whitelist_externals or allowlist_externals might be specified, not both
```

**Comment by hroncok** [comment]
@ssbarnea Do you wish to attempt to tackle this?

**Comment by ssbarnea** [comment]
I can try, I already had to do something like this for another plugin. In fact we can even neuter the feature and avoid altering the config to avoid it.

**Comment by ssbarnea** [comment]
@hroncok In fact bumping tox version is not enough because newer versions of tox did not remove the support for old whitelist_externals, only added a warning. LOTS of project did not act on these for various reasons.

The only workaround for this is to detect which one is used in current file. Have a look at another plugin where I had to do something similar: https://github.com/tox-dev/tox-ansible/blob/a26989e4144933d323f8bf443326b73bf710c3c6/src/tox_ansible/tox_helper.py#L144

In general I am ok to bump deps to avoid adding extra complexity but that one is more difficult.
