### ISSUE TITLE
Plugin incompatible with various valid tox deps  like --editable

### ISSUE THREAD

**Issue by ssbarnea** [fedora-python/tox-current-env#46]
Any project using [pip commands inside deps](https://github.com/ansible-community/molecule/blob/main/tox.ini#L51) will break when using `tox-current-env` because plugin has no idea what to. do with these.

That is even more problematic as that approach of installing dependencies is the only working method for projects that already dropped setup.py and which cannot use the classic tox commands due to known tox bugs.

```
Traceback (most recent call last):
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 421, in main
    generate_requires(
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 358, in generate_requires
    generate_tox_requirements(toxenv, requirements)
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 311, in generate_tox_requirements
    packages = convert_requirements_txt(deplines)
  File "/usr/lib/rpm/redhat/pyproject_requirements_txt.py", line 63, in convert_requirements_txt
    raise ValueError(f'{filename}: unsupported requirements file option: {line}')
ValueError: <requirements file>: unsupported requirements file option: --editable=.[docker,lint,podman,test,windows]
error: Bad exit status from /var/tmp/rpm-tmp.BW9H1d (%prep)
    line 30: second Description
    Bad exit status from /var/tmp/rpm-tmp.BW9H1d (%prep)
```

**Comment by hroncok** [comment]
This is a known limitation of the pyproject-rpm-macros. Maybe it needs to be documented. This plugin simply outputs the stuff it gets -- if you pass it e.g. to pip, it should work.

Similarly, if there are `pip install-like commands in the commands section, the `%tox` macro will fail.

For the record, the referenced tox bug here is https://github.com/tox-dev/tox/issues/2197

I don't have a good solution to this. In RPM environment, we cannot install editable installs.

**Comment by hroncok** [comment]
With my Fedora packager hat on, I might only suggest trying to split the environments -- use one for testing, one for testing+coverage. In Fedora Python packages, running coverage checks is discouraged: https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_linters

**Comment by ssbarnea** [comment]
If project has a requirements.txt file it should be enough for retrieving deps while ignorimg deps from tox.ini. Same for test-requirements.txt

@webknjaz Have a look at this and current PR on molecule. Maybe you can find a workaround?

**Comment by webknjaz** [comment]
I agree with Miro — a separate toxenv would be helpful for this.

**Comment by hroncok** [comment]
> If project has a requirements.txt file it should be enough for retrieving deps while ignorimg deps from tox.ini. Same for test-requirements.txt

That is possible with `%pyproject_buildrequires requirements.txt test-requirements.txt -r`.
