### ISSUE TITLE
RFE: Support for `dependency-groups` (PEP 735)

### ISSUE THREAD

**Issue by mtelka** [fedora-python/tox-current-env#81]
The newly released `tox 4.22.0` added support for `dependency-groups` (PEP 735) and it also switched to list its test dependencies using `dependency-groups`.

It would be great if `tox-current-env` supports `dependency-groups` similarly as it does with regular dependencies (`--print-deps-to`) and extras (`--print-extras-to`).

Thank you.

**Comment by hroncok** [comment]
Yes, I actually opened https://bugzilla.redhat.com/show_bug.cgi?id=2318849 yesterday and I planned to add support here.

The current state of tests will make this harder. I think it's time we drop tox 3 code when we do this.

**Comment by mtelka** [comment]
> The current state of tests will make this harder. I think it's time we drop tox 3 code when we do this.

I fully agree. `tox 3` is dead for almost two years now.

**Comment by hroncok** [comment]
Released in 0.0.14
